"""empty message

Revision ID: 005c6296c5a4
Revises: 0780a7edd2fe
Create Date: 2024-11-07 17:16:43.099017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '005c6296c5a4'
down_revision = '0780a7edd2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('medal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medal', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
