"""Add receipt_filename to donations table

Revision ID: 2487bd52cc54
Revises: bb9255a1dd70
Create Date: 2024-11-24 18:04:12.932758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2487bd52cc54'
down_revision = 'bb9255a1dd70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('receipt_filename')

    # ### end Alembic commands ###
