"""Add pledged_amount to Donation model

Revision ID: 254be378cf8a
Revises: dc12ca71bb50
Create Date: 2024-11-26 15:48:07.273532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '254be378cf8a'
down_revision = 'dc12ca71bb50'
branch_labels = None
depends_on = None

def upgrade():
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pledged_amount', sa.Float(), nullable=False, server_default='0'))
        batch_op.alter_column('pledged_amount', server_default=None)  # Remove the default once it's been set for all rows


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('pledged_amount')

    # ### end Alembic commands ###
