"""Add payment_type to Donation model

Revision ID: 438f65a5b778
Revises: a950184f4c0f
Create Date: 2024-11-19 14:36:05.320899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '438f65a5b778'
down_revision = 'a950184f4c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.String(length=20), nullable=True))  # Allow NULL for existing rows

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('medal',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('medal',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('payment_type')

    # ### end Alembic commands ###
