"""Add paid_status column to donations

Revision ID: 4c690fa429f2
Revises: 5a881088119c
Create Date: 2024-11-27 03:43:47.775529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c690fa429f2'
down_revision = '5a881088119c'
branch_labels = None
depends_on = None


def upgrade():
    # Add the paid_status column
    op.add_column('donations', sa.Column('paid_status', sa.Boolean(), nullable=True, server_default='false'))

    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('paid_status')

    # ### end Alembic commands ###
