"""Add donation_date field

Revision ID: 5a881088119c
Revises: 59942da157ec
Create Date: 2024-11-27 03:09:14.555750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a881088119c'
down_revision = '59942da157ec'
branch_labels = None
depends_on = None




# In your Alembic migration script
def upgrade():
    with op.batch_alter_table('user') as batch_op:
        batch_op.add_column(sa.Column('donation_date', sa.Date(), nullable=False, server_default=sa.func.now()))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('donation_date')

    # ### end Alembic commands ###
