"""Add pledge_currency to User model

Revision ID: a096aae20bde
Revises: daf3052966e2
Create Date: 2024-11-03 01:43:16.761705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a096aae20bde'
down_revision = 'daf3052966e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Set password_hash to the proper length
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),  # Adjust this if necessary
               type_=sa.String(length=255),  # Change to a suitable length (255 is common)
               existing_nullable=False)

        # Adjust the length of the address column
        batch_op.alter_column('address',
               existing_type=sa.String(length=255),
               type_=sa.String(length=200),
               existing_nullable=True)

        # Add the new columns for pledge_currency and pledged_amount
        batch_op.add_column(sa.Column('pledge_currency', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pledged_amount', sa.Numeric(10, 2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.String(length=128),
               existing_nullable=False)

        batch_op.alter_column('address',
               existing_type=sa.String(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)

        # Drop the new columns added in the upgrade
        batch_op.drop_column('pledge_currency')
        batch_op.drop_column('pledged_amount')

    # ### end Alembic commands ###
