"""Add partner_since column to User

Revision ID: bb9255a1dd70
Revises: 438f65a5b778
Create Date: 2024-11-21 19:41:19.254096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb9255a1dd70'
down_revision = '438f65a5b778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('payment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_since', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('partner_since')

    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('payment_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
