"""Add amount_paid to donations

Revision ID: dc12ca71bb50
Revises: 2487bd52cc54
Create Date: 2024-11-26 03:22:21.260100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc12ca71bb50'
down_revision = '2487bd52cc54'
branch_labels = None
depends_on = None


def upgrade():
    # ### Step 1: Add column as nullable with a default value ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))

    # ### Step 2: Populate default value ###
    op.execute("UPDATE donations SET amount_paid = 0 WHERE amount_paid IS NULL")

    # ### Step 3: Alter column to make it non-nullable ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.alter_column('amount_paid', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donations', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
