"""Add has_received_onboarding_sms column to User model

Revision ID: de41e92a2f9c
Revises: 7f91ffa76d90
Create Date: 2024-12-04 07:57:21.000411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de41e92a2f9c'
down_revision = '7f91ffa76d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_received_onboarding_sms', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('has_received_onboarding_sms')

    # ### end Alembic commands ###
